language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-lvm.gemspec
- gem install sensu-plugins-lvm-*.gem
deploy:
  provider: rubygems
  gem: sensu-plugins-lvm
  on:
    ags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    repo: sensu-plugins/sensu-plugins-lvm
